<a href="https://colab.research.google.com/github/rockbmw3/Data-Analytics-py/blob/main/icp3_summer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as np

# Create random vector of size 15 with integers 1-20
arr = np.random.randint(1, 21, size=15)

# Reshape to 3 rows and 5 columns
arr = arr.reshape(3, 5)

print("Original array:\n", arr)
print("Shape:", arr.shape)

# Replace max element in each row with 0
for i in range(arr.shape[0]):
    max_index = np.argmax(arr[i])
    arr[i, max_index] = 0

print("Array after replacing max in each row with 0:\n", arr)


Original array:
 [[ 9  6  1  3  4]
 [18  1  2  2  3]
 [ 9  1 18 18  3]]
Shape: (3, 5)
Array after replacing max in each row with 0:
 [[ 0  6  1  3  4]
 [ 0  1  2  2  3]
 [ 9  1  0 18  3]]


In [2]:
arr2 = np.arange(12, dtype=np.int32).reshape(4, 3)  # 12 elements, 4x3 shape

print("Array:\n", arr2)
print("Shape:", arr2.shape)
print("Type:", type(arr2))
print("Data type:", arr2.dtype)


Array:
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
Shape: (4, 3)
Type: <class 'numpy.ndarray'>
Data type: int32


In [3]:
matrix = np.array([[3, -2],
                   [1,  0]])

eigvals, eigvecs = np.linalg.eig(matrix)

print("Eigenvalues:\n", eigvals)
print("Right eigenvectors:\n", eigvecs)


Eigenvalues:
 [2. 1.]
Right eigenvectors:
 [[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


In [4]:
arr3 = np.array([[0, 1, 2],
                 [3, 4, 5]])

diag_sum = np.trace(arr3)  # sums main diagonal elements

print("Sum of diagonal elements:", diag_sum)


Sum of diagonal elements: 4


In [5]:
arr4 = np.array([[1, 2],
                 [3, 4],
                 [5, 6]])

print("Original shape (3x2):\n", arr4)

reshaped_arr = arr4.reshape(2, 3)

print("Reshaped array (2x3):\n", reshaped_arr)


Original shape (3x2):
 [[1 2]
 [3 4]
 [5 6]]
Reshaped array (2x3):
 [[1 2 3]
 [4 5 6]]
